### ISSUE TITLE
User Story 1: Count display

### ISSUE THREAD

**Issue by WE-dev1** [WE-dev1/calorie-and-workout-tracker-neuefische-capstone#1]
## Value proposition

As someone who wants to get in better shape
I want to see a displayed count and be able to raise it
So that I can track my calories

## Description

![Image](https://user-images.githubusercontent.com/98795399/229323899-d4f991da-0366-408f-81d6-2f0b582a241d.png)

## Acceptance criteria

- [ ]  A dynamic counter is displayed
- [ ]  I can put in a number
- [ ]  to raise the count with a button press

## Tasks

- [ ] count state (in _app)
- [ ] return a headline with the count 
- [ ] create a form
-> with an input that only accepts numbers
-> and a button that adds the input value to the count
