### ISSUE TITLE
User Story 2: Add consumed

### ISSUE THREAD

**Issue by WE-dev1** [WE-dev1/calorie-and-workout-tracker-neuefische-capstone#2]
## Value proposition

As a user
I want to see a List of my entries
So that I keep track of everything I consumed

## Description

![Image](https://user-images.githubusercontent.com/98795399/229363398-389454e2-d78a-40ab-b97e-23384fc8661d.png)

## Acceptance criteria

- [ ]  When I press the "add" button my Product is added to a visible list
- [ ]  I see when I consumed it
- [ ]  I can delete list items if I made a mistake

## Tasks

- add name to the daily state / a name state
- add current time value to the daily state
- map over the array of items to create visible list items
- add a button to delete the list item

**Comment by toshydev** [comment]
LGTM
