### ISSUE TITLE
User Story 13: Set & Display workouts on the calendar

### ISSUE THREAD

**Issue by WE-Kaito** [WE-dev1/calorie-and-workout-tracker-neuefische-capstone#28]
User Story 13: Set & Display workouts on the calendar
## Value proposition

As a user
I want to set a workout routine
so I can see them on my calendar

## Description

![Image](https://user-images.githubusercontent.com/98795399/231186083-f9dfbbe9-8672-4e44-9105-0e9c1a6e7c09.png)

## Acceptance criteria

- [ ]  At the bottom of the workout page, I can toggle an Edit mode
- [ ] In edit mode, I can click on the workouts to set the order of my training routine
- [ ] clicking on the rest button will add a rest day to the routine
- [ ] the added elements are displayed
- [ ] clicking on the set button will save my routine and set an interval starting from the current day

## Tasks

- [ ] not sure how to approach it yet

**Comment by AnjaSiewert** [comment]
Hi Enrico, LGTM! Just one thing I noticed:
How can you toggle the edit mode? Is there a button/an SVG or something else? On the wireframe I don't see anything
