### ISSUE TITLE
User Story 2X: animations

### ISSUE THREAD

**Issue by WE-dev1** [WE-dev1/calorie-and-workout-tracker-neuefische-capstone#39]

**Comment by WE-dev1** [comment]
User Story 16: Progress Bar
## Value proposition

As a user
I want to see a bar that displays my consumed calories
so that I enjoy using the App more

## Description




















![Image](https://user-images.githubusercontent.com/98795399/231192731-741ff507-ce12-4150-805c-4babdd5b2ab2.png)













## Acceptance criteria

- [ ]  On the homepage a progress bar is displayed above the caories left
- [ ]  It fills depending on on how much calories are left
- [ ] on 100% the bar should be red

## Tasks

- [ ]  draw on canvas?

**Comment by Satttoshi** [comment]
Define your task a little more, to structure your strategy and resolve upcoming bugs and infrastructural issues earlier.
Looking forwards for your filling bar.

**Comment by CoderMarkus** [comment]
LGTM. The bar is filling. It looks lovely.
