### ISSUE TITLE
User Story 4: Set daily max calories

### ISSUE THREAD

**Issue by WE-dev1** [WE-dev1/calorie-and-workout-tracker-neuefische-capstone#4]
## Value proposition

As a user
I want to write down and save a number
to set my daily goal

## Description

![Image](https://user-images.githubusercontent.com/98795399/229386503-0303e8f2-72b8-4461-9483-d6a76dfa6703.png)

## Acceptance criteria

- [ ]  There should be a "settings" page
- [ ]  I can set a new daily goal in a simple form
- [ ] The calorie count displays how much calories I have left...
- [ ] ... and changes if the goal is exceeded

## Tasks

- [ ] create `.../pages/edit/index.js`
- [ ] add a navigation
- [ ] add a form to the edit page
- [ ] create a `dailyMaxCalories `state that updates when the form is sent
- [ ] check if  todaysCalories > dailyMaxCalories and make todaysCalories depiction responsive

**Comment by djfarly** [comment]
You are describing two numbers, right? The goal and the current calorie count.
I'd make the value proposition a bit clearer and not only talk about a "number" but about the concrete thing you want to set: "daily calorie goal".

This user story is about setting my goal. I am not sure about the last to AC, they seem like they belong to another user story as they are about showing the goal in comparison to the second number.

**Comment by toshydev** [comment]
LGTM ✅
