### ISSUE TITLE
User Story 5: Calendar on Homepage

### ISSUE THREAD

**Issue by WE-dev1** [WE-dev1/calorie-and-workout-tracker-neuefische-capstone#5]
## Value proposition

As a user
I want to see a calendar 
So that I know when I kept track

## Description

![Image](https://user-images.githubusercontent.com/98795399/229387768-56745635-7a77-42ef-91a7-8613cc5ebd0f.png)

## Acceptance criteria

- [ ]  The daily form should be hidden like the list so that
- [ ]  I can see a calendar which marks the current day

## Tasks

- [ ] move the form on the homepage like in User Story 3
- [ ] add a live calendar from a library
- [ ] (when the date changes, the todaysCalories state should be reset to 0)

**Comment by NinaBusz** [comment]
Hi 👋 
Nice project! Picture explains most of it. 😄 

I'm just wondering one thing: is there a highlight on the days you have entered calories or do you have to click through the days to see the days you have/haven't entered anything? Cause the Value proposition says: "So that I know when I kept track" sounds bit like an overview

**Comment by WE-dev1** [comment]
Thx, this will be handled in the next User Story!

**Comment by Sascha-Pionczewski** [comment]
lgtm!
