### ISSUE TITLE
User Story 6: History on Calendar

### ISSUE THREAD

**Issue by WE-dev1** [WE-dev1/calorie-and-workout-tracker-neuefische-capstone#6]
## Value proposition

As a user
I want to have a history of my tracked days
So that I can see if I am doing well

## Description

![Image](https://user-images.githubusercontent.com/98795399/229388219-382ec1a5-e55c-4c6b-bdbd-ecddc2e18cdf.png)

## Acceptance criteria

- [ ] Every tracked day should be marked either green or red depending if the goal was exceeded

## Tasks

- [ ] ?create a "history" state and add a new object with relevant data when the day changes
- [ ] each object in the history should mark its corresponding date in the calendar by success

**Comment by manukao** [comment]
lgtm 👍
