### ISSUE TITLE
User Story 7: Save custom dishes

### ISSUE THREAD

**Issue by WE-dev1** [WE-dev1/calorie-and-workout-tracker-neuefische-capstone#7]
## Value proposition

As a user
I want to save my favourite meals
So that I don't have to know their nutritional value after.

## Description

![Image](https://user-images.githubusercontent.com/98795399/229388696-a26758c1-7089-4a2f-acef-7be3e82b7c11.png)

## Acceptance criteria

- [ ] In the edit page there should display a link to my custom meals
- [ ] On the dishes page is a button that links to the creation form
- [ ] I can add additional information and  save my custom meal
- [ ] After pressing the submit button I can see an entry on the dishes page

## Tasks

- [ ]

**Comment by augustinanders** [comment]
Looks good to me :)
