### ISSUE TITLE
User Story 8: Dish details page

### ISSUE THREAD

**Issue by WE-dev1** [WE-dev1/calorie-and-workout-tracker-neuefische-capstone#8]
## Value proposition

As a user
I want to see all the custom food i saved
So that I have all the information that is relevant to me

## Description

![Image](https://user-images.githubusercontent.com/98795399/229389656-25a07f05-aa83-48af-8953-1bb53e6e05af.png)

## Acceptance criteria

- [ ] The entrys on the dishes page are clickable links
- [ ] ...that lead to a corresponding details page
- [ ] I can delete an entry

## Tasks

- [ ] create `pages/edit/dishes/[id].js`
- [ ] display the full data of the form in User Story 7
- [ ] add a button which deletes the entry

**Comment by Satttoshi** [comment]
Beautiful, LGTM. 

You may want to define your tasks further for future code reviews

**Comment by AnjaSiewert** [comment]
LGTM in general :)
One thing I would amend: in tasks you have written that there is a button for deletion but I cannot see it on the wireframe
